{{- if .Values.autoscaler.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.appName }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName}}
  minReplicas: {{ .Values.autoscaler.limits.minReplica }}
  maxReplicas: {{ .Values.autoscaler.limits.maxReplica }}
  targetCPUUtilizationPercentage: {{ .Values.autoscaler.limits.cpuUtil }}
{{- end }}
