{{- if .Values.ingress.enabled -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
labels:
  app: {{ .Values.appName }}
  env: {{ .Values.env }}
rules:
{{- range .Values.ingress.hosts }}
- host: {{ .host }}
  http:
    paths:
  {{- range .paths }}
- path: {{ .path }}
  pathType: Prefix
  backend:
    service:
      name: {{ .serviceName }}
      port:
        number: {{ default 80 .servicePort }}
  {{- end }}
{{- end }}

{{- end }}
